### ISSUE TITLE
actions stopped running

### ISSUE THREAD

**Issue by brettmc** [codelicia/php-nightly#59]
Hi. The github action for this repo last ran on 13/11/2023, and no new updates have been published since.

I can see the following notice: `This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.`

**Comment by malukenho** [comment]
Hey there, @brettmc! 👋 Thanks a bunch for giving me the heads up! 🙌 I really appreciate it. 

Just wanted to let you know that I've enabled the Github action again. Once everything is working smoothly, I'll be sure to close the issue. Thanks again for your help! 😊

**Comment by malukenho** [comment]
It is working!
